#!/usr/bin/env perl
use strict;
use warnings;

use Log::Dispatch;
use Log::Dispatch::Log::Stash;
use Log::Stash::Output::ZeroMQ;

my $log = Log::Dispatch->new;

$log->add(Log::Dispatch::Log::Stash->new(
      name      => 'myapp_aggregate_log',
      min_level => 'debug',
      output    => Log::Stash::Output::ZeroMQ->new(
          connect => 'tcp://192.168.0.1:5558', # Central log server.
      ),
));
$log->warn($_) for qw/ foo bar baz /;

sleep 1; # Allow time for ZeroMQ to actually flush the messages..

